export const APP_NAME = 'LexIQ Iraq';

export const DEFAULT_PAGE_SIZE = 20;
export const MAX_PAGE_SIZE = 100;

export enum SystemRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  FIRM_ADMIN = 'FIRM_ADMIN',
  SENIOR_LAWYER = 'SENIOR_LAWYER',
  LAWYER = 'LAWYER',
  TRAINEE = 'TRAINEE',
  RESEARCHER = 'RESEARCHER',
  FINANCE_CLERK = 'FINANCE_CLERK',
  READ_ONLY_VIEWER = 'READ_ONLY_VIEWER',
}
